# Generated by Django 4.2.5 on 2023-09-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollmenmt_membershipplan_trainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollmenmt',
            new_name='Enrollment',
        ),
    ]
