# Generated by Django 4.2.5 on 2023-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectdate', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=200)),
                ('logout', models.CharField(max_length=200)),
                ('selectworkout', models.CharField(max_length=200)),
                ('trainer', models.CharField(max_length=200)),
            ],
        ),
    ]
