# Generated by Django 4.2.5 on 2023-10-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_attendance_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='userprofile',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
