# Generated by Django 4.2.5 on 2023-10-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_enrollment_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='userprofile',
        ),
    ]
