# Generated by Django 4.2.5 on 2023-10-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_remove_enrollment_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
